name: flutter_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.1.0
  onesignal_flutter: ^5.0.3
  google_fonts: ^6.1.0
  page_transition: ^2.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.1.14
  fluttertoast: ^8.2.2
  cached_network_image: ^3.3.0
  lottie: ^2.6.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
#  dio: ^4.0.6
  custom_refresh_indicator: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svgs/